<x-app-layout>
    <x-slot name="header">
        <div class="flex justify-between items-center">
            <h2 class="font-semibold text-xl text-gray-800 leading-tight">
                {{ __('Test Pixel') }}: {{ $pixel->name }}
            </h2>
            <a href="{{ route('pixels.index') }}" class="inline-flex items-center px-4 py-2 bg-gray-600 border border-transparent rounded-md font-semibold text-xs text-white uppercase tracking-widest hover:bg-gray-700 focus:bg-gray-700 active:bg-gray-800 focus:outline-none focus:ring-2 focus:ring-gray-500 focus:ring-offset-2 transition ease-in-out duration-150">
                {{ __('Back to Pixels') }}
            </a>
        </div>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-xl sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">
                    <div class="bg-gray-50 rounded-lg p-6 mb-6">
                        <h3 class="text-lg font-medium text-gray-900 mb-4">Test Your Pixel</h3>
                        <p class="text-gray-600 mb-4">
                            We've created a test page with your pixel installed so you can verify it's working correctly.
                            This test simulates a visitor coming to your website.
                        </p>
                        <div class="flex items-center">
                            <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6 text-yellow-500 mr-2" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
                            </svg>
                            <p class="text-sm text-gray-600">
                                <strong>Note:</strong> The test page will open in a new tab. Return to this page after visiting the test page to see the results.
                            </p>
                        </div>
                    </div>
                    
                    <div class="mb-10 flex justify-center">
                        <a href="{{ $testPageUrl }}" target="_blank" class="inline-flex items-center px-6 py-3 bg-blue-600 border border-transparent rounded-md font-semibold text-sm text-white uppercase tracking-widest hover:bg-blue-700 focus:bg-blue-700 active:bg-blue-800 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2 transition ease-in-out duration-150">
                            <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 mr-2" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 15l-2 5L9 9l11 4-5 2zm0 0l5 5M7.188 2.239l.777 2.897M5.136 7.965l-2.898-.777M13.95 4.05l-2.122 2.122m-5.657 5.656l-2.12 2.122" />
                            </svg>
                            Open Test Page
                        </a>
                    </div>
                    
                    <div class="mb-6">
                        <h3 class="text-lg font-medium text-gray-900 mb-4">Tracking Results</h3>
                        
                        <div class="grid grid-cols-1 md:grid-cols-3 gap-6">
                            <div class="bg-white p-6 rounded-lg border border-gray-200 shadow-sm">
                                <div class="flex items-center justify-between mb-4">
                                    <h4 class="font-medium text-gray-700">Visitor Count</h4>
                                    <span class="bg-blue-100 text-blue-800 text-xs font-semibold px-2.5 py-0.5 rounded">Last 24 hours</span>
                                </div>
                                <p class="text-3xl font-bold text-gray-900">{{ $pixel->visitor_count }}</p>
                                <div class="mt-2 text-sm text-gray-500">Total visitors tracked by this pixel</div>
                            </div>
                            
                            <div class="bg-white p-6 rounded-lg border border-gray-200 shadow-sm">
                                <div class="flex items-center justify-between mb-4">
                                    <h4 class="font-medium text-gray-700">Lead Count</h4>
                                    <span class="bg-green-100 text-green-800 text-xs font-semibold px-2.5 py-0.5 rounded">Last 24 hours</span>
                                </div>
                                <p class="text-3xl font-bold text-gray-900">{{ $pixel->lead_count }}</p>
                                <div class="mt-2 text-sm text-gray-500">Total leads generated by this pixel</div>
                            </div>
                            
                            <div class="bg-white p-6 rounded-lg border border-gray-200 shadow-sm">
                                <div class="flex items-center justify-between mb-4">
                                    <h4 class="font-medium text-gray-700">Status</h4>
                                    <span class="bg-{{ $pixel->is_verified ? 'green' : 'yellow' }}-100 text-{{ $pixel->is_verified ? 'green' : 'yellow' }}-800 text-xs font-semibold px-2.5 py-0.5 rounded">
                                        {{ $pixel->is_verified ? 'Verified' : 'Not Verified' }}
                                    </span>
                                </div>
                                <p class="text-3xl font-bold text-gray-900">{{ $pixel->is_active ? 'Active' : 'Inactive' }}</p>
                                <div class="mt-2 text-sm text-gray-500">
                                    {{ $pixel->is_verified ? 'Pixel is verified and collecting data' : 'Pixel needs to be verified on your domain' }}
                                </div>
                            </div>
                        </div>
                    </div>
                    
                    <div class="mt-8 flex justify-between">
                        <a href="{{ route('pixels.code', $pixel) }}" class="text-blue-600 hover:text-blue-900">
                            <span>Get Installation Code</span>
                        </a>
                        <a href="{{ route('pixels.show', $pixel) }}" class="inline-flex items-center px-4 py-2 bg-blue-600 border border-transparent rounded-md font-semibold text-xs text-white uppercase tracking-widest hover:bg-blue-700 focus:bg-blue-700 active:bg-blue-800 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2 transition ease-in-out duration-150">
                            {{ __('View Pixel Details') }}
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</x-app-layout> 